### PR TITLE
add Man-mode support

### PR DESCRIPTION
**Pull request by bmalehorn**
Save and restore buffers in `Man-mode`, the major mode created by
`M-x man`.

`Man-mode` is pretty simple to save and restore; each buffer is
read-only and can be re-generated through the `man` unix command.

### CODE REVIEW

**Comment by bmalehorn** [comment]
Ugh, Emacs 24 vs 25 problem. Working on a fix.

**Comment by ffevotte** [comment]
Thanks for working on this. I don't have much time to help you now, but I'll try to integrate it during the Christmas holidays.

**Comment by bmalehorn** [comment]
Maybe `Man-mode` isn't so simple, due to async stuff.

Tried it in Emacs 24. Manually ran `M-x man`, closed & reopened Emacs. Worked fine.

The test is failing because `Man-mode-hook` isn't running my hook. The hooks do run in 25 + manually, 25 + tests, and 24 + manually, but not 24 + tests. I suspect I need to add a sleep statement somewhere but I don't understand the test case format enough to make it work. I'll work more on this later.

**Comment by bmalehorn** [comment]
Yay, I got it to work! Thoughts?

**Comment by ffevotte** [comment]
Many thanks!

**Pull request merged**
